Fix type unification regression
A patch introduced in b3cb13a73d09770138f81d0757105807bb1bd7f3 (#8)
broke a previously working use case included in issue8.kit:

    Error: ./issue8.kit:4: Assigned value must match the type of the lvalue it's assigned to:

      @./test.kit:4:9
           4        a = 1;
                        ^

        Expected type:  Void
          Actual type:  Int8

Changing the type of null to a pointer to void instead of a generic
pointer was suggested in #8 instead (discussion) and it really seems
like it both does what #8 did and fixes the regression.