Fix box test on Mac OS
The test was failing with:

    tests/Kit/CompilerSpec.hs:41:7:
    1) Kit.Compiler, Successful compile tests, tests/compile-src/box.kit
         uncaught exception: IOException of type OtherError
         callProcess: /usr/bin/cc "-Werror" "-Ibuild/include" "-c" "build/lib/box/kit_Greeter.c" "-o" "build/obj/box/kit_Greeter.o" "-D_GNU_SOURCE" "-D_BSD_SOURCE" "-D_DEFAULT_SOURCE" "-std=c99" "-pedantic" "-O3" "-Os" "-U__BLOCKS__" "-Wno-expansion-to-defined" "-Wno-gnu-zero-variadic-macro-arguments" (exit 1): failed

The cc output (obtained manually) was as follows:

    build/lib/box/kit_Greeter.c:17:53: error: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Werror,-Wformat]
            printf((char *) "Hellooo from Int64 %li\n", *__this);
                                                ~~~     ^~~~~~~
                                                %lli
    1 error generated.

Using long long instead of just long should provide a consistent
behaviour on Linux and Mac OS.